name: test

on:
  pull_request:
    branches:
      - "main"

jobs:
  hello_world_job:
    runs-on: [self-hosted, macOS, x64]

    steps:
      - uses: actions/checkout@master

      - name: Install correct Bundler version
        run: echo "Hello, self hosted runner!"
